const WORLD_CUP_DATA = {
  countries: [
    { code: "MEX", name: "Mexico", displayName: "México", flag: "🇲🇽", group: "A" },
    { code: "ZAF", name: "South Africa", displayName: "Sudáfrica", flag: "🇿🇦", group: "A" },
    { code: "KOR", name: "South Korea", displayName: "Corea del Sur", flag: "🇰🇷", group: "A" },
    { code: "CZE", name: "Czech Republic", displayName: "Republica Checa", flag: "🇨🇿", group: "A" },
    { code: "CAN", name: "Canada", displayName: "Canadá", flag: "🇨🇦", group: "B" },
    { code: "BIH", name: "Bosnia and Herzegovina", displayName: "Bosnia y Herzegovina", flag: "🇧🇦", group: "B" },
    { code: "QAT", name: "Qatar", displayName: "Catar", flag: "🇶🇦", group: "B" },
    { code: "SUI", name: "Switzerland", displayName: "Suiza", flag: "🇨🇭", group: "B" },
    { code: "BRA", name: "Brazil", displayName: "Brasil", flag: "🇧🇷", group: "C" },
    { code: "MAR", name: "Morocco", displayName: "Marruecos", flag: "🇲🇦", group: "C" },
    { code: "HAI", name: "Haiti", displayName: "Haití", flag: "🇭🇹", group: "C" },
    { code: "SCO", name: "Scotland", displayName: "Escocia", flag: "🏴", group: "C" },
    { code: "USA", name: "United States", displayName: "Estados Unidos", flag: "🇺🇸", group: "D" },
    { code: "PAR", name: "Paraguay", displayName: "Paraguay", flag: "🇵🇾", group: "D" },
    { code: "AUS", name: "Australia", displayName: "Australia", flag: "🇦🇺", group: "D" },
    { code: "TUR", name: "Turkey", displayName: "Turquía", flag: "🇹🇷", group: "D" },
    { code: "GER", name: "Germany", displayName: "Alemania", flag: "🇩🇪", group: "E" },
    { code: "CUW", name: "Curacao", displayName: "Curazao", flag: "🇨🇼", group: "E" },
    { code: "CIV", name: "Ivory Coast", displayName: "Costa de Marfil", flag: "🇨🇮", group: "E" },
    { code: "ECU", name: "Ecuador", displayName: "Ecuador", flag: "🇪🇨", group: "E" },
    { code: "NED", name: "Netherlands", displayName: "Holanda", flag: "🇳🇱", group: "F" },
    { code: "JPN", name: "Japan", displayName: "Japón", flag: "🇯🇵", group: "F" },
    { code: "SWE", name: "Sweden", displayName: "Suecia", flag: "🇸🇪", group: "F" },
    { code: "TUN", name: "Tunisia", displayName: "Túnez", flag: "🇹🇳", group: "F" },
    { code: "BEL", name: "Belgium", displayName: "Bélgica", flag: "🇧🇪", group: "G" },
    { code: "EGY", name: "Egypt", displayName: "Egipto", flag: "🇪🇬", group: "G" },
    { code: "IRN", name: "Iran", displayName: "Irán", flag: "🇮🇷", group: "G" },
    { code: "NZL", name: "New Zealand", displayName: "Nueva Zelanda", flag: "🇳🇿", group: "G" },
    { code: "ESP", name: "Spain", displayName: "España", flag: "🇪🇸", group: "H" },
    { code: "CPV", name: "Cape Verde", displayName: "Cabo Verde", flag: "🇨🇻", group: "H" },
    { code: "KSA", name: "Saudi Arabia", displayName: "Arabia Saudita", flag: "🇸🇦", group: "H" },
    { code: "URU", name: "Uruguay", displayName: "Uruguay", flag: "🇺🇾", group: "H" },
    { code: "FRA", name: "France", displayName: "Francia", flag: "🇫🇷", group: "I" },
    { code: "SEN", name: "Senegal", displayName: "Senegal", flag: "🇸🇳", group: "I" },
    { code: "IRQ", name: "Iraq", displayName: "Irak", flag: "🇮🇶", group: "I" },
    { code: "NOR", name: "Norway", displayName: "Noruega", flag: "🇳🇴", group: "I" },
    { code: "ARG", name: "Argentina", displayName: "Argentina", flag: "🇦🇷", group: "J" },
    { code: "ALG", name: "Algeria", displayName: "Argelia", flag: "🇩🇿", group: "J" },
    { code: "AUT", name: "Austria", displayName: "Austria", flag: "🇦🇹", group: "J" },
    { code: "JOR", name: "Jordan", displayName: "Jordania", flag: "🇯🇴", group: "J" },
    { code: "POR", name: "Portugal", displayName: "Portugal", flag: "🇵🇹", group: "K" },
    { code: "COD", name: "Congo", displayName: "Congo", flag: "🇨🇩", group: "K" },
    { code: "UZB", name: "Uzbekistan", displayName: "Uzbekistán", flag: "🇺🇿", group: "K" },
    { code: "COL", name: "Colombia", displayName: "Colombia", flag: "🇨🇴", group: "K" },
    { code: "ENG", name: "England", displayName: "Inglaterra", flag: "🏴", group: "L" },
    { code: "CRO", name: "Croatia", displayName: "Croacia", flag: "🇭🇷", group: "L" },
    { code: "GHA", name: "Ghana", displayName: "Ghana", flag: "🇬🇭", group: "L" },
    { code: "PAN", name: "Panama", displayName: "Panamá", flag: "🇵🇦", group: "L" }
  ],
  participants: [
    "Carlos Escobar", "Juan Escobar Zaldivar", "Carlos Escobar", "Roberto Escobar Rico",
    "Carlos Escobar", "Valente Escobar Flores", "Carlos Escobar", "Fernanda Lopez Morales",
    "Carlos Escobar", "Lorenzo Escobar Lopez", "Carlos Escobar", "Valentina Escobar Lopez",
    "Carlos Escobar", "Joel Ramirez Escobar", "Carlos Escobar", "Lorenzo Escobar Zaldivar",
    "Carlos Escobar", "Julio Escobar Vega", "Carlos Escobar", "Alejandro Escobar Jr",
    "Carlos Escobar", "Genoveva Garcia", "Carlos Escobar", "Alejandra Villarreal",
    "Ricardo Escobar Flores", "Nicole Escobar", "Claudia Romero Perez", "Manuel Escobar",
    "Ricardo Escobar Romero", "Santiago Escobar", "Claudio Escobar Romero", "Memo Escobar",
    "Pollopug Escobar", "Haakon Escobar", "Mundialito TV", "Samantha Escobar",
    "Yazmin Romero", "Ricardo Valente Escobar", "Riclaud Escobar", "Blanca Aguirre",
    "Aaron Escobar", "Luis Escobar Lopez", "Jorge Escobar", "Gabriela Lopez Flores",
    "Regina Escobar", "Matias Villegas", "Ximena Escobar", "Aislinn Villagran Villegas"
  ],
  matches: [
    { number: 1, a: "MEX", b: "ZAF", group: "A", date: "11 de junio", time: "13:00 h CDMX", venue: "Mexico City Stadium" },
    { number: 2, a: "KOR", b: "CZE", group: "A", date: "12 de junio", time: "20:00 h CDMX", venue: "Guadalajara Stadium" },
    { number: 3, a: "CAN", b: "BIH", group: "B", date: "12 de junio", time: "13:00 h CDMX", venue: "Toronto Stadium" },
    { number: 4, a: "USA", b: "PAR", group: "D", date: "12 de junio", time: "19:00 h CDMX", venue: "Los Angeles Stadium" },
    { number: 5, a: "HAI", b: "SCO", group: "C", date: "13 de junio", time: "19:00 h CDMX", venue: "Boston Stadium" },
    { number: 6, a: "AUS", b: "TUR", group: "D", date: "12 de junio", time: "22:00 h CDMX", venue: "Vancouver Stadium" },
    { number: 7, a: "BRA", b: "MAR", group: "C", date: "13 de junio", time: "16:00 h CDMX", venue: "New York New Jersey Stadium" },
    { number: 8, a: "QAT", b: "SUI", group: "B", date: "13 de junio", time: "13:00 h CDMX", venue: "San Francisco Bay Area Stadium" },
    { number: 9, a: "CIV", b: "ECU", group: "E", date: "14 de junio", time: "17:00 h CDMX", venue: "Philadelphia Stadium" },
    { number: 10, a: "GER", b: "CUW", group: "E", date: "14 de junio", time: "11:00 h CDMX", venue: "Houston Stadium" },
    { number: 11, a: "NED", b: "JPN", group: "F", date: "14 de junio", time: "14:00 h CDMX", venue: "Dallas Stadium" },
    { number: 12, a: "SWE", b: "TUN", group: "F", date: "14 de junio", time: "20:00 h CDMX", venue: "Monterrey Stadium" },
    { number: 13, a: "KSA", b: "URU", group: "H", date: "15 de junio", time: "16:00 h CDMX", venue: "Miami Stadium" },
    { number: 14, a: "ESP", b: "CPV", group: "H", date: "15 de junio", time: "10:00 h CDMX", venue: "Atlanta Stadium" },
    { number: 15, a: "IRN", b: "NZL", group: "G", date: "15 de junio", time: "19:00 h CDMX", venue: "Los Angeles Stadium" },
    { number: 16, a: "BEL", b: "EGY", group: "G", date: "15 de junio", time: "13:00 h CDMX", venue: "Seattle Stadium" },
    { number: 17, a: "FRA", b: "SEN", group: "I", date: "16 de junio", time: "13:00 h CDMX", venue: "New York New Jersey Stadium" },
    { number: 18, a: "IRQ", b: "NOR", group: "I", date: "16 de junio", time: "16:00 h CDMX", venue: "Boston Stadium" },
    { number: 19, a: "ARG", b: "ALG", group: "J", date: "16 de junio", time: "19:00 h CDMX", venue: "Kansas City Stadium" },
    { number: 20, a: "AUT", b: "JOR", group: "J", date: "15 de junio", time: "22:00 h CDMX", venue: "San Francisco Bay Area Stadium" },
    { number: 21, a: "GHA", b: "PAN", group: "L", date: "17 de junio", time: "17:00 h CDMX", venue: "Toronto Stadium" },
    { number: 22, a: "ENG", b: "CRO", group: "L", date: "17 de junio", time: "14:00 h CDMX", venue: "Dallas Stadium" },
    { number: 23, a: "POR", b: "COD", group: "K", date: "17 de junio", time: "11:00 h CDMX", venue: "Houston Stadium" },
    { number: 24, a: "UZB", b: "COL", group: "K", date: "17 de junio", time: "20:00 h CDMX", venue: "Mexico City Stadium" },
    { number: 25, a: "CZE", b: "ZAF", group: "A", date: "18 de junio", time: "10:00 h CDMX", venue: "Atlanta Stadium" },
    { number: 26, a: "SUI", b: "BIH", group: "B", date: "18 de junio", time: "13:00 h CDMX", venue: "Los Angeles Stadium" },
    { number: 27, a: "CAN", b: "QAT", group: "B", date: "18 de junio", time: "16:00 h CDMX", venue: "Vancouver Stadium" },
    { number: 28, a: "MEX", b: "KOR", group: "A", date: "18 de junio", time: "19:00 h CDMX", venue: "Guadalajara Stadium" },
    { number: 29, a: "BRA", b: "HAI", group: "C", date: "19 de junio", time: "18:30 h CDMX", venue: "Philadelphia Stadium" },
    { number: 30, a: "SCO", b: "MAR", group: "C", date: "19 de junio", time: "16:00 h CDMX", venue: "Boston Stadium" },
    { number: 31, a: "TUR", b: "PAR", group: "D", date: "19 de junio", time: "21:00 h CDMX", venue: "San Francisco Bay Area Stadium" },
    { number: 32, a: "USA", b: "AUS", group: "D", date: "19 de junio", time: "13:00 h CDMX", venue: "Seattle Stadium" },
    { number: 33, a: "GER", b: "CIV", group: "E", date: "20 de junio", time: "14:00 h CDMX", venue: "Toronto Stadium" },
    { number: 34, a: "ECU", b: "CUW", group: "E", date: "20 de junio", time: "18:00 h CDMX", venue: "Kansas City Stadium" },
    { number: 35, a: "NED", b: "SWE", group: "F", date: "20 de junio", time: "11:00 h CDMX", venue: "Houston Stadium" },
    { number: 36, a: "TUN", b: "JPN", group: "F", date: "19 de junio", time: "22:00 h CDMX", venue: "Monterrey Stadium" },
    { number: 37, a: "URU", b: "CPV", group: "H", date: "21 de junio", time: "16:00 h CDMX", venue: "Miami Stadium" },
    { number: 38, a: "ESP", b: "KSA", group: "H", date: "21 de junio", time: "10:00 h CDMX", venue: "Atlanta Stadium" },
    { number: 39, a: "BEL", b: "IRN", group: "G", date: "21 de junio", time: "13:00 h CDMX", venue: "Los Angeles Stadium" },
    { number: 40, a: "NZL", b: "EGY", group: "G", date: "21 de junio", time: "19:00 h CDMX", venue: "Vancouver Stadium" },
    { number: 41, a: "NOR", b: "SEN", group: "I", date: "22 de junio", time: "18:00 h CDMX", venue: "New York New Jersey Stadium" },
    { number: 42, a: "FRA", b: "IRQ", group: "I", date: "22 de junio", time: "15:00 h CDMX", venue: "Philadelphia Stadium" },
    { number: 43, a: "ARG", b: "AUT", group: "J", date: "22 de junio", time: "11:00 h CDMX", venue: "Dallas Stadium" },
    { number: 44, a: "JOR", b: "ALG", group: "J", date: "22 de junio", time: "21:00 h CDMX", venue: "San Francisco Bay Area Stadium" },
    { number: 45, a: "ENG", b: "GHA", group: "L", date: "23 de junio", time: "14:00 h CDMX", venue: "Boston Stadium" },
    { number: 46, a: "PAN", b: "CRO", group: "L", date: "23 de junio", time: "17:00 h CDMX", venue: "Toronto Stadium" },
    { number: 47, a: "POR", b: "UZB", group: "K", date: "23 de junio", time: "11:00 h CDMX", venue: "Houston Stadium" },
    { number: 48, a: "COL", b: "COD", group: "K", date: "23 de junio", time: "20:00 h CDMX", venue: "Guadalajara Stadium" },
    { number: 49, a: "SCO", b: "BRA", group: "C", date: "24 de junio", time: "16:00 h CDMX", venue: "Miami Stadium" },
    { number: 50, a: "MAR", b: "HAI", group: "C", date: "24 de junio", time: "16:00 h CDMX", venue: "Atlanta Stadium" },
    { number: 51, a: "SUI", b: "CAN", group: "B", date: "24 de junio", time: "13:00 h CDMX", venue: "Vancouver Stadium" },
    { number: 52, a: "BIH", b: "QAT", group: "B", date: "24 de junio", time: "13:00 h CDMX", venue: "Seattle Stadium" },
    { number: 53, a: "CZE", b: "MEX", group: "A", date: "24 de junio", time: "19:00 h CDMX", venue: "Mexico City Stadium" },
    { number: 54, a: "ZAF", b: "KOR", group: "A", date: "24 de junio", time: "19:00 h CDMX", venue: "Monterrey Stadium" },
    { number: 55, a: "CUW", b: "CIV", group: "E", date: "25 de junio", time: "14:00 h CDMX", venue: "Philadelphia Stadium" },
    { number: 56, a: "ECU", b: "GER", group: "E", date: "25 de junio", time: "14:00 h CDMX", venue: "New York New Jersey Stadium" },
    { number: 57, a: "JPN", b: "SWE", group: "F", date: "25 de junio", time: "17:00 h CDMX", venue: "Dallas Stadium" },
    { number: 58, a: "TUN", b: "NED", group: "F", date: "25 de junio", time: "17:00 h CDMX", venue: "Kansas City Stadium" },
    { number: 59, a: "TUR", b: "USA", group: "D", date: "25 de junio", time: "20:00 h CDMX", venue: "Los Angeles Stadium" },
    { number: 60, a: "PAR", b: "AUS", group: "D", date: "25 de junio", time: "20:00 h CDMX", venue: "San Francisco Bay Area Stadium" },
    { number: 61, a: "NOR", b: "FRA", group: "I", date: "26 de junio", time: "13:00 h CDMX", venue: "Boston Stadium" },
    { number: 62, a: "SEN", b: "IRQ", group: "I", date: "26 de junio", time: "13:00 h CDMX", venue: "Toronto Stadium" },
    { number: 63, a: "EGY", b: "IRN", group: "G", date: "26 de junio", time: "21:00 h CDMX", venue: "Seattle Stadium" },
    { number: 64, a: "NZL", b: "BEL", group: "G", date: "26 de junio", time: "21:00 h CDMX", venue: "Vancouver Stadium" },
    { number: 65, a: "CPV", b: "KSA", group: "H", date: "26 de junio", time: "18:00 h CDMX", venue: "Houston Stadium" },
    { number: 66, a: "URU", b: "ESP", group: "H", date: "26 de junio", time: "18:00 h CDMX", venue: "Guadalajara Stadium" },
    { number: 67, a: "PAN", b: "ENG", group: "L", date: "27 de junio", time: "15:00 h CDMX", venue: "New York New Jersey Stadium" },
    { number: 68, a: "CRO", b: "GHA", group: "L", date: "27 de junio", time: "15:00 h CDMX", venue: "Philadelphia Stadium" },
    { number: 69, a: "ALG", b: "AUT", group: "J", date: "27 de junio", time: "20:00 h CDMX", venue: "Kansas City Stadium" },
    { number: 70, a: "JOR", b: "ARG", group: "J", date: "27 de junio", time: "20:00 h CDMX", venue: "Dallas Stadium" },
    { number: 71, a: "COL", b: "POR", group: "K", date: "27 de junio", time: "17:30 h CDMX", venue: "Miami Stadium" },
    { number: 72, a: "COD", b: "UZB", group: "K", date: "27 de junio", time: "17:30 h CDMX", venue: "Atlanta Stadium" }
  ],
  bracket: {
    rounds: [
      { name: "Dieciseisavos", matches: [
        { a: "MEX", scoreA: 2, b: "AUS", scoreB: 1, winner: "MEX" },
        { a: "BRA", scoreA: 3, b: "SCO", scoreB: 0, winner: "BRA" },
        { a: "FRA", scoreA: 2, b: "NOR", scoreB: 0, winner: "FRA" },
        { a: "ENG", scoreA: 1, b: "GHA", scoreB: 0, winner: "ENG" },
        { a: "ARG", scoreA: 4, b: "JOR", scoreB: 1, winner: "ARG" },
        { a: "POR", scoreA: 2, b: "UZB", scoreB: 0, winner: "POR" },
        { a: "ESP", scoreA: 3, b: "CPV", scoreB: 1, winner: "ESP" },
        { a: "GER", scoreA: 2, b: "CIV", scoreB: 1, winner: "GER" },
        { a: "USA", scoreA: 2, b: "TUR", scoreB: 1, winner: "USA" },
        { a: "NED", scoreA: 2, b: "TUN", scoreB: 0, winner: "NED" },
        { a: "BEL", scoreA: 3, b: "NZL", scoreB: 1, winner: "BEL" },
        { a: "COL", scoreA: 2, b: "COD", scoreB: 1, winner: "COL" },
        { a: "URU", scoreA: 2, b: "KSA", scoreB: 0, winner: "URU" },
        { a: "MAR", scoreA: 1, b: "HAI", scoreB: 0, winner: "MAR" },
        { a: "SUI", scoreA: 2, b: "PAR", scoreB: 1, winner: "SUI" },
        { a: "CRO", scoreA: 2, b: "SWE", scoreB: 1, winner: "CRO" }
      ] },
      { name: "Octavos", matches: [
        { a: "BRA", scoreA: 2, b: "MEX", scoreB: 1, winner: "BRA" },
        { a: "FRA", scoreA: 2, b: "ENG", scoreB: 1, winner: "FRA" },
        { a: "ARG", scoreA: 3, b: "POR", scoreB: 2, winner: "ARG" },
        { a: "ESP", scoreA: 2, b: "GER", scoreB: 1, winner: "ESP" },
        { a: "USA", scoreA: 2, b: "NED", scoreB: 1, winner: "USA" },
        { a: "COL", scoreA: 2, b: "BEL", scoreB: 1, winner: "COL" },
        { a: "URU", scoreA: 2, b: "MAR", scoreB: 0, winner: "URU" },
        { a: "CRO", scoreA: 2, b: "SUI", scoreB: 1, winner: "CRO" }
      ] },
      { name: "Cuartos", matches: [
        { a: "BRA", scoreA: 2, b: "FRA", scoreB: 1, winner: "BRA" },
        { a: "ARG", scoreA: 2, b: "ESP", scoreB: 1, winner: "ARG" },
        { a: "COL", scoreA: 2, b: "USA", scoreB: 1, winner: "COL" },
        { a: "URU", scoreA: 2, b: "CRO", scoreB: 1, winner: "URU" }
      ] },
      { name: "Semifinal", matches: [
        { a: "ARG", scoreA: 2, b: "BRA", scoreB: 1, winner: "ARG" },
        { a: "URU", scoreA: 2, b: "COL", scoreB: 1, winner: "URU" }
      ] },
      { name: "Final", matches: [
        { a: "ARG", scoreA: 3, b: "URU", scoreB: 1, winner: "ARG" }
      ] }
    ],
    champion: "ARG"
  },
  drawVideoUrl: "https://www.youtube.com/embed/VIDEO_ID_AQUI"
};
